This notebook will serve as the master notebook which the TAs can run from start to finish

In [1]:
import pandas as pd
import numpy as np
from src.utils import get_batches, shuffle, train_val_split


%load_ext autoreload
%autoreload 2

In [2]:
# Define the path to the data
data_path = './data/essay_df.pkl'
df = pd.read_pickle(data_path)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8764 entries, 0 to 10683
Data columns (total 8 columns):
essay_id         8764 non-null int64
essay_set        8764 non-null int64
essay            8764 non-null object
domain1_score    8764 non-null int64
essays_embed     8764 non-null object
word_count       8764 non-null int64
max_score        8764 non-null float64
norm_score       8764 non-null float64
dtypes: float64(2), int64(4), object(2)
memory usage: 616.2+ KB


In [14]:
X = np.array(df['essays_embed'])
y = np.array(df['norm_score'])

In [15]:
X_stacked = np.stack(X, axis=0)
print(X_stacked.shape)

(8764, 600, 100)


In [16]:
X_flat = np.reshape(X_stacked, [X_stacked.shape[0], -1])
print(X_flat.shape)

(8764, 60000)


In [17]:
X_shuffled, y_shuffled = shuffle(X_flat, y)

In [18]:
print(X_shuffled.shape)

(8764, 60000)


In [19]:
X_train, y_train, X_val, y_val = train_val_split(X_shuffled, y_shuffled, train_prop=0.8)

In [51]:
from src.mlp import MLP
input_dim = X_train.shape[1]
batch_size = 100

batch_gen = get_batches(X_train, y_train, batch_size, net_type='mlp')

my_net = MLP(input_dim=input_dim, hidden_dims=[100, 100], num_classes=12, l2_reg=1e-4)

In [52]:
my_net.train(gen=batch_gen, X_val=X_val, y_val=y_val, n_epochs=20, lr=1e-2)

loss for counter 5 is 2.438948392868042
counter 5: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 10 is 2.4793944358825684
counter 10: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 15 is 2.471740245819092
counter 15: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 20 is 1.693276286125183
counter 20: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 25 is 1.7523139715194702
counter 25: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 30 is 1.819976806640625
counter 30: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 35 is 1.9171377420425415
counter 35: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 40 is 1.9840341806411743
counter 40: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 45 is 1.967331886291504
counter 45: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 4 8 8 8 8 8 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 50 is 1.8063957691192627
counter 50: valid acc = 0.0
[8 8 8 8 8 8 8 4 8 4 4 4 8 4 8 8 8 8 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 55 is 2.08632230758667
counter 55: valid acc = 0.0
[8 8 8 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 60 is 2.356614112854004
counter 60: valid acc = 0.0
[8 8 8 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 65 is 2.042902946472168
counter 65: valid acc = 0.0
[8 8 8 8 8 8 8 4 8 4 4 4 8 4 8 8 8 8 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 70 is 2.078446626663208
counter 70: valid acc = 0.0
[8 8 8 8 8 8 8 4 8 4 4 4 8 4 8 8 8 8 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 75 is 2.369800090789795
counter 75: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 4 8 4 8 8 8 8 8 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 80 is 2.412123918533325
counter 80: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 85 is 2.403811454772949
counter 85: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 90 is 1.4451932907104492
counter 90: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 95 is 1.4683969020843506
counter 95: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 100 is 1.4790095090866089
counter 100: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 105 is 1.6119147539138794
counter 105: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 110 is 1.6529134511947632
counter 110: valid acc = 0.0
[8 8 8 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 115 is 1.547882318496704
counter 115: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 120 is 1.4297293424606323
counter 120: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 125 is 2.1785104274749756
counter 125: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 8 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 130 is 2.3758883476257324
counter 130: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 8 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 135 is 1.9979307651519775
counter 135: valid acc = 0.0
[8 4 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 140 is 1.977400302886963
counter 140: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 145 is 2.3021695613861084
counter 145: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 150 is 2.3396856784820557
counter 150: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 155 is 2.327465772628784
counter 155: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 160 is 1.139379620552063
counter 160: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 165 is 1.1088624000549316
counter 165: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 170 is 1.0852668285369873
counter 170: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 175 is 1.3017349243164062
counter 175: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 180 is 1.3724181652069092
counter 180: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 185 is 1.25709068775177
counter 185: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 190 is 1.2268190383911133
counter 190: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 195 is 2.233076810836792
counter 195: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 200 is 2.32006573677063
counter 200: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 205 is 1.8836615085601807
counter 205: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 210 is 1.8009802103042603
counter 210: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 215 is 2.2652828693389893
counter 215: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 4 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 220 is 2.2906882762908936
counter 220: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 225 is 2.281104564666748
counter 225: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 230 is 1.071022629737854
counter 230: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 235 is 1.0311866998672485
counter 235: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 240 is 1.0051891803741455
counter 240: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 245 is 1.2421436309814453
counter 245: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 250 is 1.3184566497802734
counter 250: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 8 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 255 is 1.2071529626846313
counter 255: valid acc = 0.0
[8 8 4 8 4 8 4 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 260 is 1.183332085609436
counter 260: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 8 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 265 is 2.164684534072876
counter 265: valid acc = 0.0
[8 8 4 8 4 8 4 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 270 is 2.2120351791381836
counter 270: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 275 is 1.763846755027771
counter 275: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 280 is 1.6453059911727905
counter 280: valid acc = 0.22317351400852203
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 285 is 2.2506792545318604
counter 285: valid acc = 0.22031962871551514
[6 6 6 6 6 6 6 6 8 6 6 6 8 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 290 is 2.2660675048828125
counter 290: valid acc = 0.2009132355451584
[8 8 6 8 6 8 6 6 8 6 6 6 8 6 8 6 8 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 295 is 2.264549732208252
counter 295: valid acc = 0.10331050306558609
[8 8 8 8 8 8 8 8 8 8 8 6 8 6 8 8 8 8 6 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 300 is 1.0952444076538086
counter 300: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 305 is 1.0331060886383057
counter 305: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 310 is 0.9928126931190491
counter 310: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 315 is 1.2212504148483276
counter 315: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 320 is 1.292829155921936
counter 320: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 325 is 1.1821876764297485
counter 325: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 330 is 1.1570578813552856
counter 330: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 8 4 4 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 335 is 2.1205499172210693
counter 335: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 340 is 2.1392228603363037
counter 340: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 345 is 1.6829922199249268
counter 345: valid acc = 0.027397260069847107
[8 8 8 8 8 8 8 8 8 4 6 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 350 is 1.5466808080673218
counter 350: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 355 is 2.241425037384033
counter 355: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 360 is 2.250638961791992
counter 360: valid acc = 0.2226027399301529
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 365 is 2.256990671157837
counter 365: valid acc = 0.21632419526576996
[8 6 6 6 6 6 6 6 8 6 6 6 8 6 6 6 8 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 370 is 1.1204191446304321
counter 370: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 375 is 1.0342766046524048
counter 375: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 380 is 0.9811902642250061
counter 380: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 385 is 1.2032158374786377
counter 385: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 390 is 1.2717278003692627
counter 390: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 395 is 1.1608136892318726
counter 395: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 400 is 1.1353691816329956
counter 400: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 405 is 2.099794626235962
counter 405: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 410 is 2.088498592376709
counter 410: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 415 is 1.6225711107254028
counter 415: valid acc = 0.21746575832366943
[6 6 6 6 6 6 6 6 8 6 6 6 8 6 6 6 8 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 420 is 1.4776785373687744
counter 420: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 425 is 2.233103036880493
counter 425: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 430 is 2.2377700805664062
counter 430: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 435 is 2.2503502368927
counter 435: valid acc = 0.2214611917734146
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 440 is 1.141333818435669
counter 440: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 445 is 1.0309003591537476
counter 445: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 450 is 0.9669733047485352
counter 450: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 455 is 1.1863489151000977
counter 455: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 460 is 1.253129005432129
counter 460: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 465 is 1.1412677764892578
counter 465: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 470 is 1.115979790687561
counter 470: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 475 is 2.08971905708313
counter 475: valid acc = 0.0
[8 8 4 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 480 is 2.0423848628997803
counter 480: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 485 is 1.5648518800735474
counter 485: valid acc = 0.2226027399301529
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 490 is 1.4137020111083984
counter 490: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 495 is 2.2260055541992188
counter 495: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 500 is 2.224780559539795
counter 500: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 505 is 2.2425119876861572
counter 505: valid acc = 0.22317351400852203
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 510 is 1.162802815437317
counter 510: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 515 is 1.0245602130889893
counter 515: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 520 is 0.9500662684440613
counter 520: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 525 is 1.170359492301941
counter 525: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 530 is 1.2357351779937744
counter 530: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 535 is 1.122448205947876
counter 535: valid acc = 0.0
[8 8 4 8 8 8 8 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 540 is 1.0971966981887817
counter 540: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 545 is 2.0838370323181152
counter 545: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 550 is 1.988680124282837
counter 550: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 555 is 1.4985640048980713
counter 555: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 560 is 1.340578317642212
counter 560: valid acc = 0.22488585114479065
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 565 is 2.2220866680145264
counter 565: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 570 is 2.2105655670166016
counter 570: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 575 is 2.232780933380127
counter 575: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 580 is 1.1869810819625854
counter 580: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 585 is 1.0144730806350708
counter 585: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 590 is 0.9293167591094971
counter 590: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 595 is 1.154919147491455
counter 595: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 600 is 1.2183748483657837
counter 600: valid acc = 0.0
[8 8 4 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 605 is 1.1034413576126099
counter 605: valid acc = 0.0
[8 8 4 8 4 8 4 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 610 is 1.0777140855789185
counter 610: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 615 is 2.077342987060547
counter 615: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 620 is 1.9138739109039307
counter 620: valid acc = 0.13413241505622864
[8 8 6 8 8 8 8 8 8 6 6 6 8 6 8 8 8 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 625 is 1.4142467975616455
counter 625: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 630 is 1.2496564388275146
counter 630: valid acc = 0.2254566252231598
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 635 is 2.2246363162994385
counter 635: valid acc = 0.2254566252231598
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 640 is 2.193781614303589
counter 640: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 645 is 2.2191832065582275
counter 645: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 650 is 1.2113419771194458
counter 650: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 655 is 0.99649977684021
counter 655: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 660 is 0.9030553698539734
counter 660: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 665 is 1.1401848793029785
counter 665: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 670 is 1.1998507976531982
counter 670: valid acc = 0.0
[8 8 4 8 4 8 4 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 675 is 1.0836251974105835
counter 675: valid acc = 0.0
[8 8 4 8 4 8 4 4 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 680 is 1.0566461086273193
counter 680: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 4 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 685 is 2.0612785816192627
counter 685: valid acc = 0.0
[8 8 4 8 8 8 8 8 8 4 4 4 8 4 8 8 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 690 is 1.7970054149627686
counter 690: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 695 is 1.305001139640808
counter 695: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 700 is 1.139453649520874
counter 700: valid acc = 0.2254566252231598
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 705 is 2.2374236583709717
counter 705: valid acc = 0.22659817337989807
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 710 is 2.168889045715332
counter 710: valid acc = 0.22602739930152893
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 715 is 2.192234992980957
counter 715: valid acc = 0.22374428808689117
[6 6 6 6 6 6 6 6 8 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 720 is 1.2238432168960571
counter 720: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 725 is 0.9607689380645752
counter 725: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 730 is 0.8712957501411438
counter 730: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 735 is 1.1281964778900146
counter 735: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 740 is 1.1785032749176025
counter 740: valid acc = 0.0
[8 8 4 4 4 8 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 745 is 1.063344120979309
counter 745: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 750 is 1.0349698066711426
counter 750: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 755 is 2.010378122329712
counter 755: valid acc = 0.0
[8 8 4 8 8 8 4 4 8 4 4 4 8 4 8 8 8 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 760 is 1.6161518096923828
counter 760: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 765 is 1.1811786890029907
counter 765: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 770 is 1.032273292541504
counter 770: valid acc = 0.23915524780750275
[6 6 6 6 6 6 6 6 9 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 775 is 2.2509658336639404
counter 775: valid acc = 0.24942922592163086
[6 6 6 6 6 6 6 6 9 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 780 is 2.1067330837249756
counter 780: valid acc = 0.24200913310050964
[6 6 6 6 6 6 6 6 9 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 785 is 2.1096231937408447
counter 785: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 790 is 1.208893895149231
counter 790: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 795 is 0.8930244445800781
counter 795: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 800 is 0.8431296944618225
counter 800: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 805 is 1.1271520853042603
counter 805: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 810 is 1.1534875631332397
counter 810: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 4 4 4 4 4 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 815 is 1.0469506978988647
counter 815: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 4 4 4 4 4 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 820 is 1.0202187299728394
counter 820: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 825 is 1.8652063608169556
counter 825: valid acc = 0.0
[8 8 4 4 4 4 4 4 8 4 4 4 8 4 8 4 8 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 830 is 1.4148509502410889
counter 830: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 835 is 1.085652232170105
counter 835: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 840 is 0.9737644195556641
counter 840: valid acc = 0.45205479860305786
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 845 is 2.166719436645508
counter 845: valid acc = 0.45205479860305786
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 850 is 1.9149370193481445
counter 850: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 855 is 1.9244294166564941
counter 855: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 860 is 1.1745034456253052
counter 860: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 865 is 0.8218899965286255
counter 865: valid acc = 0.0
[4 4 4 4 4 4 4 4 8 4 4 4 4 4 4 4 4 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 870 is 0.8350646495819092
counter 870: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 875 is 1.1510391235351562
counter 875: valid acc = 0.0
[8 8 4 4 4 8 4 4 8 4 4 4 8 4 8 8 8 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 880 is 1.1281497478485107
counter 880: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 885 is 1.0357539653778076
counter 885: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 890 is 1.0166250467300415
counter 890: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 895 is 1.5810707807540894
counter 895: valid acc = 0.45205479860305786
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 900 is 1.2846661806106567
counter 900: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 905 is 1.0385489463806152
counter 905: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 910 is 0.9568448662757874
counter 910: valid acc = 0.45205479860305786
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 915 is 1.850556492805481
counter 915: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 920 is 1.7239989042282104
counter 920: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 925 is 1.7898461818695068
counter 925: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 930 is 1.07231867313385
counter 930: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 935 is 0.7838267683982849
counter 935: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 940 is 0.8369061350822449
counter 940: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 945 is 1.1760714054107666
counter 945: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 950 is 1.0936311483383179
counter 950: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 955 is 1.0217616558074951
counter 955: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 960 is 1.019047737121582
counter 960: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 4 8 8 4 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 965 is 1.2748795747756958
counter 965: valid acc = 0.45205479860305786
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 970 is 1.2032595872879028
counter 970: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 975 is 1.0207250118255615
counter 975: valid acc = 0.22431506216526031
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 980 is 0.9490153789520264
counter 980: valid acc = 0.21917808055877686
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 9]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 985 is 1.652971625328064
counter 985: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 990 is 1.6439151763916016
counter 990: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 995 is 1.766884446144104
counter 995: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 1000 is 0.8452533483505249
counter 1000: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 1005 is 0.7553697824478149
counter 1005: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 1010 is 0.975233793258667
counter 1010: valid acc = 0.0
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


loss for counter 1015 is 1.4367343187332153
counter 1015: valid acc = 0.0
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[12  9  9  6  9  9  6  9  9  3  9  6 12  6 12  9 12  3  9  3]


KeyboardInterrupt: 